add badge icon and list of crowdActionMetadata to badgeDTO
CollActionteam/collaction_api pull request #124
Opened 2023-03-05 22:07 UTC by pkhanpara

First stab at #119 
- added CrowdActionMetadata {id, title} to domain
- added list of CrowdActionMetadata to BadgeDTO
- also added accessiblityOutline string link to the BadgeDTO

Not sure how or where to update the list of CrowdActions associated with the badge. Please review it and leave your suggestions here. I will try to address them promptly.

2023-05-18 02:20 UTC, imReset commented
Please review the changes and inform me if any further adjustments are needed.

2023-05-18 11:23 UTC, MichaelSlatteryDev requested changes
Besides the `accessibilityOutline` name it looks all good to me 👍

2023-05-18 11:23 UTC, MichaelSlatteryDev commented on src/infrastructure/mongo/persistence/badge.persistence.ts
> +    readonly accessibilityOutline?: string;
This should be called icon. Not accessibilityOutline. This applies to everywhere where accessibilityOutline is used in this PR.

2023-05-19 01:47 UTC, Xazin commented
Thanks @imReset

2023-05-22 12:55 UTC, MichaelSlatteryDev approved these changes

2023-05-22 12:56 UTC, merged